[gcp]
saas_project_id = ea-agentspacepj
region = us-central1
tfstate_bucket_name = gemini-bq-query-analyzer-tfstate
api_jar_bucket_name = api-jar-for-gemini-bq-query-analyzer-cn28
; tfstate_bucket_name = tfstate-for-gemini-bq-query-analyzer-khqc
