import os
import json

# スクリプトがあるディレクトリ（root/tools）を取得
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

def generate_tfvars(
        env_path=os.path.join(BASE_DIR, '../.env'),
        tfvars_path=os.path.join(BASE_DIR, '../terraform/terraform.tfvars')
):
    """
    .env から共通変数と TENANTS_JSON を読み込み、
    Terraform の map(object) 形式に対応した .tfvars を生成する。
    """
    if not os.path.exists(env_path):
        print(f"エラー: {env_path} が見つかりません。")
        return

    common_vars = {}
    tenants_data = {}

    with open(env_path, 'r', encoding='utf-8') as f:
        # シェルの環境変数読み込みに近い挙動でパース
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            if '=' in line:
                key, value = line.split('=', 1)
                key = key.strip()
                # 引用符の除去（シングル/ダブル両対応）
                value = value.strip().strip("'").strip('"')

                if key == "TENANTS_JSON":
                    tenants_data = json.loads(value)
                else:
                    common_vars[key.lower()] = value

    # tfvars 形式に整形して書き出し
    with open(tfvars_path, 'w', encoding='utf-8') as f:
        f.write("# Generated by generate_tfvars.py - DO NOT EDIT MANUALLY\n\n")

        # 1. 共通変数の書き出し
        max_key_len = max(len(k) for k in common_vars.keys()) if common_vars else 0
        for key, value in common_vars.items():
            # TENANTS_JSON に含まれる重複キーは出力しない
            if key in ["customer_project_id", "slack_webhook_url", "gcs_bucket_name", "worst_query_limit", "time_range_interval"]:
                continue
            padding = " " * (max_key_len - len(key))
            f.write(f'{key}{padding} = "{value}"\n')

        # 2. tenants マップの書き出し
        if tenants_data:
            f.write("\ntenants = {\n")
            for tenant_id, config in tenants_data.items():
                f.write(f'  "{tenant_id}" = {{\n')
                for k, v in config.items():
                    f.write(f'    {k:<20} = "{v}"\n')
                f.write("  }\n")
            f.write("}\n")

    print(f"完了: {tfvars_path} をマルチテナント形式で生成しました。")

if __name__ == "__main__":
    generate_tfvars()
