import os
import json
import re

# スクリプトがあるディレクトリ（root/tools）を取得
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

def generate_tfvars(
        env_path=os.path.join(BASE_DIR, '../.env'),
        tfvars_path=os.path.join(BASE_DIR, '../terraform/terraform.tfvars')
):
    """
    .env から共通変数とマルチラインの TENANTS_JSON を読み込み、
    Terraform の map(object) 形式に対応した .tfvars を生成する。
    """
    if not os.path.exists(env_path):
        print(f"エラー: {env_path} が見つかりません。")
        return

    with open(env_path, 'r', encoding='utf-8') as f:
        content = f.read()

    common_vars = {}
    tenants_data = {}

    # 1. 共通設定の抽出 (SAAS_PROJECT_ID, REGION, BQ_ANTIPATTERN_ANALYZER_URL)
    # 単純な key="value" 形式を正規表現で探す
    simple_vars = re.findall(r'^([A-Z_]+)\s*=\s*["\']?([^"\']+)["\']?', content, re.MULTILINE)
    for key, value in simple_vars:
        if key != "TENANTS_JSON":
            common_vars[key.lower()] = value

    # 2. TENANTS_JSON の抽出
    # TENANTS_JSON='{ ... }' の構造を抽出（シングルクォーテーションで囲まれた中身を取得）
    tenants_match = re.search(r'TENANTS_JSON\s*=\s*\'(.*?)\'', content, re.DOTALL)
    if tenants_match:
        try:
            tenants_json_str = tenants_match.group(1).strip()
            tenants_data = json.loads(tenants_json_str)
        except json.JSONDecodeError as e:
            print(f"エラー: TENANTS_JSON のパースに失敗しました。構造を確認してください。\n{e}")
            return

    # tfvars 形式に整形して書き出し
    with open(tfvars_path, 'w', encoding='utf-8') as f:
        f.write("# Generated by generate_tfvars.py - DO NOT EDIT MANUALLY\n\n")

        # 1. 共通設定セクション
        f.write("# ==========================================\n")
        f.write("# 共通設定 (SaaS 基盤側)\n")
        f.write("# ==========================================\n")

        max_key_len = max(len(k) for k in common_vars.keys()) if common_vars else 0
        for key, value in common_vars.items():
            padding = " " * (max_key_len - len(key))
            f.write(f'{key}{padding} = "{value}"\n')

        # 2. テナント設定セクション
        if tenants_data:
            f.write("\n# ==========================================\n")
            f.write("# マルチテナント設定 (マップ 形式)\n")
            f.write("# ==========================================\n")
            f.write("tenants = {\n")
            for tenant_id, config in tenants_data.items():
                f.write(f'  "{tenant_id}" = {{\n')
                for k, v in config.items():
                    # Webhook URL などの長い文字列に備えてパディングを調整
                    f.write(f'    {k:<20} = "{v}"\n')
                f.write("  }\n")
            f.write("}\n")

    print(f"完了: {tfvars_path} を正常に生成しました。")

if __name__ == "__main__":
    generate_tfvars()
