import configparser
import json
import os
import sys

from google.cloud import storage

# --- 設定パスの定義 ---
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_CONFIG_INI = os.path.join(BASE_DIR, "base_config.ini")
ENV_PATH = os.path.join(BASE_DIR, "env.txt")
TFVARS_DIR = os.path.join(BASE_DIR, "terraform")
TFVARS_PATH = os.path.join(TFVARS_DIR, "terraform.tfvars")
BACKEND_TF_PATH = os.path.join(TFVARS_DIR, "backend.tf")

TENANTS_CONFIG_PATH = "config/tenants.json"


def main():
    # 1. base_config.ini の読み込み
    if not os.path.exists(BASE_CONFIG_INI):
        print(f"エラー: {BASE_CONFIG_INI} が見つかりません。")
        sys.exit(1)

    config = configparser.ConfigParser()
    config.read(BASE_CONFIG_INI, encoding="utf-8")

    try:
        saas_id = config["gcp"]["saas_project_id"]
        region = config["gcp"]["region"]
        tfstate_bucket = config["gcp"]["tfstate_bucket_name"]
        api_jar_bucket = config["gcp"]["api_jar_bucket_name"]
    except KeyError as e:
        print(f"エラー: base_config.ini の設定項目が不足しています: {e}")
        sys.exit(1)

    # 2. GCSからテナント設定を取得
    try:
        gcs_client = storage.Client()
        blob = gcs_client.bucket(tfstate_bucket).blob(TENANTS_CONFIG_PATH)
        tenants = json.loads(blob.download_as_text())
        print(f"テナント設定を取得しました: {len(tenants)} テナント")
    except Exception as e:
        print(
            f"エラー: GCSからテナント設定の取得に失敗しました: gs://{tfstate_bucket}/{TENANTS_CONFIG_PATH}: {e}"
        )
        sys.exit(1)

    # 3. .env の書き出し
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write("# ==========================================\n")
        f.write("# 共通設定 (SaaS 基盤側)\n")
        f.write("# ==========================================\n")
        f.write(f'SAAS_PROJECT_ID="{saas_id}"\n')
        f.write(f'REGION="{region}"\n')
        f.write(f'API_JAR_BUCKET="{api_jar_bucket}"\n\n')

        f.write("# ==========================================\n")
        f.write("# マルチテナント設定 (JSON 形式)\n")
        f.write("# ==========================================\n")
        f.write(f"TENANTS_JSON='{json.dumps(tenants, ensure_ascii=False, indent=2)}'\n")

    # 4. terraform.tfvars の書き出し
    if not os.path.exists(TFVARS_DIR):
        os.makedirs(TFVARS_DIR)

    with open(TFVARS_PATH, "w", encoding="utf-8") as f:
        f.write("# Generated by generate_configs.py - DO NOT EDIT MANUALLY\n")
        f.write("# ==========================================\n")
        f.write("# 共通設定 (SaaS 基盤側)\n")
        f.write("# ==========================================\n")
        f.write(f'saas_project_id     = "{saas_id}"\n')
        f.write(f'region              = "{region}"\n')
        f.write(f'api_jar_bucket_name = "{api_jar_bucket}"\n\n')

        f.write("# ==========================================\n")
        f.write("# マルチテナント設定 (マップ 形式)\n")
        f.write("# ==========================================\n")
        f.write("tenants = {\n")
        for tid, cfg in tenants.items():
            f.write(f'  "{tid}" = {{\n')
            for k, v in cfg.items():
                f.write(f'    {k:<25} = "{v}"\n')
            f.write("  }\n")
        f.write("}\n")

    # 5. backend.tf の書き出し
    with open(BACKEND_TF_PATH, "w", encoding="utf-8") as f:
        f.write("# Generated from base_config.ini - DO NOT EDIT\n")
        f.write("terraform {\n")
        f.write('  backend "gcs" {\n')
        f.write(f'    bucket = "{tfstate_bucket}"\n')
        f.write('    prefix = "terraform/state"\n')
        f.write("  }\n")
        f.write("}\n")

    print(f"完了: 処理テナント数: {len(tenants)}")


if __name__ == "__main__":
    main()
